name: Telegram Bot

on:
  push:
    branches:
      - main
  workflow_dispatch: # manual trigger
  schedule:
    - cron: "0 */6 * * *" # restart every 6 hours (GitHub limits)

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirement.txt ]; then pip install -r requirements.txt; fi

      - name: Run bot
        run: |
          python r.py
